"""Initial schema: core_memories, core_suspended_actions, core_knowledge, sabaq_evidence

Revision ID: 822cb633d5c8
Revises: 
Create Date: 2026-09-12 01:14:14.604440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '822cb633d5c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Required before core_knowledge's `embedding` column can use the Vector type below.
    # Not auto-detected by autogenerate - the throwaway DB this revision was generated
    # against already had the extension enabled manually; a genuinely fresh VPS Postgres
    # will not, and CREATE TABLE would fail with "type vector does not exist" without this.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_knowledge',
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=768), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_knowledge_domain'), 'core_knowledge', ['domain'], unique=False)
    op.create_table('core_memories',
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_memories_session_id'), 'core_memories', ['session_id'], unique=False)
    op.create_table('core_suspended_actions',
    sa.Column('nonce', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('request_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('nonce')
    )
    op.create_index(op.f('ix_core_suspended_actions_session_id'), 'core_suspended_actions', ['session_id'], unique=False)
    op.create_table('sabaq_evidence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('domain_namespace', sa.String(), nullable=False),
    sa.Column('provenance', sa.String(), nullable=False),
    sa.Column('evidence_version', sa.Integer(), nullable=False),
    sa.Column('search_content', sa.String(), nullable=False),
    sa.Column('structured_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('source_reference', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sabaq_evidence_domain_namespace'), 'sabaq_evidence', ['domain_namespace'], unique=False)
    op.create_index(op.f('ix_sabaq_evidence_source_reference'), 'sabaq_evidence', ['source_reference'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sabaq_evidence_source_reference'), table_name='sabaq_evidence')
    op.drop_index(op.f('ix_sabaq_evidence_domain_namespace'), table_name='sabaq_evidence')
    op.drop_table('sabaq_evidence')
    op.drop_index(op.f('ix_core_suspended_actions_session_id'), table_name='core_suspended_actions')
    op.drop_table('core_suspended_actions')
    op.drop_index(op.f('ix_core_memories_session_id'), table_name='core_memories')
    op.drop_table('core_memories')
    op.drop_index(op.f('ix_core_knowledge_domain'), table_name='core_knowledge')
    op.drop_table('core_knowledge')
    # ### end Alembic commands ###
