import logging
from typing import Dict, Any, Optional
from src.brain_core.action_engine.contracts import ActionRequest, ActionCategory
from src.intelligence_domains.ndr.communication_repository import CommunicationRepository
from src.intelligence_domains.ndr.reply_parser import CustomerReplyParser

logger = logging.getLogger(__name__)

class CommunicationEngine:
    """
    Executes outbound communications based on ActionRequests generated by the Orchestrator.
    Currently supports WhatsApp and IVR simulations.
    """
    def __init__(self, repository: CommunicationRepository, reply_parser: CustomerReplyParser = None, executor=None, ccc_builder=None):
        self.repository = repository
        self.reply_parser = reply_parser
        self.executor = executor
        self.ccc_builder = ccc_builder

    async def dispatch_action(self, awb_no: str, action: ActionRequest) -> bool:
        """
        Translates an ActionRequest into a physical communication.
        Returns True if successfully dispatched.
        """
        if not action:
            return False

        logger.info(f"[CommunicationEngine] Dispatching action for AWB {awb_no}: {action.category.value}")

        # Hydrate the immutable CCC Snapshot
        ccc_snapshot = None
        call_context = None
        if self.ccc_builder and action.directive:
            try:
                ccc = await self.ccc_builder.build(action)
                ccc_snapshot = ccc.model_dump()
                
                # Project into Customer-Safe Call Context for SUNEHRI
                projection = self.ccc_builder.project(ccc)
                call_context = projection.model_dump()
            except Exception as e:
                logger.error(f"[CommunicationEngine] Failed to hydrate CCC Snapshot: {e}")
                # We do not fall back here, we let the executor use its fallback if call_context is None

        # Explicit Execution Intent Boundary
        if action.execution_intent:
            if action.execution_intent.channel.value == "VOICE":
                if not self.executor:
                    logger.error("[CommunicationEngine] Cannot execute VOICE intent: CustomerEngagementExecutor not configured.")
                    return False
                await self.executor.execute_engagement(action, call_context=call_context, ccc_snapshot=ccc_snapshot)
                return True
            else:
                logger.error(f"[CommunicationEngine] Unsupported explicit execution channel: {action.execution_intent.channel}")
                return False

        # Legacy Path for actions without explicit intent
        if action.category == ActionCategory.HUMAN_ASSISTANCE:
            return await self._trigger_concierge_escalation(awb_no, action)
        
        logger.error(f"[CommunicationEngine] Dispatch rejected: Missing execution_intent for non-legacy action category {action.category.value}.")
        return False

    async def _send_whatsapp_message(self, awb_no: str, action: ActionRequest) -> bool:
        # The Orchestrator's justification usually contains the intended customer message
        # In a real setup, we'd extract the precise `customer_message` from the Recommendation.
        message = action.reasoning 
        
        # Log to MongoDB
        interaction_id = await self.repository.log_interaction(
            awb_no=awb_no,
            channel="whatsapp",
            direction="outbound",
            content=message,
            metadata={"action_type": action.parameters.get("action_type")}
        )
        logger.info(f"[WhatsApp] AWB {awb_no}: Sent '{message}' (Saved ID: {interaction_id})")
        
        # TODO: Call actual WhatsApp BSP API (e.g., Meta/Twilio/Wati) here
        return True

    async def _trigger_concierge_escalation(self, awb_no: str, action: ActionRequest) -> bool:
        message = f"CASE ESCALATED: {action.reasoning}"
        interaction_id = await self.repository.log_interaction(
            awb_no=awb_no,
            channel="internal_concierge",
            direction="outbound",
            content=message,
            metadata={"urgency": action.parameters.get("urgency", "HIGH")}
        )
        logger.info(f"[Concierge] AWB {awb_no}: Escalated (Saved ID: {interaction_id})")
        return True

    async def handle_inbound_reply(self, awb_no: str, channel: str, message: str) -> str:
        """
        Handles incoming customer replies (e.g. from a webhook) and uses the LLM parser to determine outcome.
        """
        # Parse the outcome using LLM
        resolved_outcome = None
        if self.reply_parser:
            parsed = await self.reply_parser.parse_reply(message)
            resolved_outcome = parsed.model_dump()
            logger.info(f"[{channel.upper()}] Parsed intent for AWB {awb_no}: {parsed.intent}")

        interaction_id = await self.repository.log_interaction(
            awb_no=awb_no,
            channel=channel,
            direction="inbound",
            content=message,
            metadata={"resolved_outcome": resolved_outcome} if resolved_outcome else None
        )
        logger.info(f"[{channel.upper()}] Received reply for AWB {awb_no}: '{message}' (Saved ID: {interaction_id})")
        return interaction_id
